// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUhMz-cgrSUrzJI6-x4ZBz5xfDE0iPlPg',
    appId: '1:403235724688:web:857bbbf00dbc695ceba715',
    messagingSenderId: '403235724688',
    projectId: 'chatapp-c47ab',
    authDomain: 'chatapp-c47ab.firebaseapp.com',
    storageBucket: 'chatapp-c47ab.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsg4pEaFJWO2PWV460rq97aEp2bTLyKDs',
    appId: '1:403235724688:android:779815decb4c6b22eba715',
    messagingSenderId: '403235724688',
    projectId: 'chatapp-c47ab',
    storageBucket: 'chatapp-c47ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvcQQt2Z_SrZnnNXDNbxRwsnTe_biT_zk',
    appId: '1:403235724688:ios:6cd76fc25b142f6ceba715',
    messagingSenderId: '403235724688',
    projectId: 'chatapp-c47ab',
    storageBucket: 'chatapp-c47ab.appspot.com',
    iosClientId: '403235724688-h5afvurbunu9mmlnbmh5fpi33bmu89o4.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvcQQt2Z_SrZnnNXDNbxRwsnTe_biT_zk',
    appId: '1:403235724688:ios:6cd76fc25b142f6ceba715',
    messagingSenderId: '403235724688',
    projectId: 'chatapp-c47ab',
    storageBucket: 'chatapp-c47ab.appspot.com',
    iosClientId: '403235724688-h5afvurbunu9mmlnbmh5fpi33bmu89o4.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
